import { buildOptions } from './lib/tampermonkey'

import type { RollupOptions } from 'rollup'

const config: RollupOptions[] = [
  buildOptions({
    id: 'annict-work-links',
    name: 'Annict Work Links',
    version: '0.2.2',
    description: 'Annict の作品ページに「しょぼいカレンダー」「MyAnimeList」「AniList」へのリンクを追加します。',
    author: 'SlashNephy <spica@starry.blue>',
    match: 'https://annict.com/*',
    connect: ['raw.githubusercontent.com'],
    grant: 'GM_xmlhttpRequest',
    icon: 'https://www.google.com/s2/favicons?sz=64&domain=annict.com',
  }),
  buildOptions({
    id: 'dominion-online-auto-table-setter',
    name: 'dominion.games Auto Table Setter',
    version: '0.3.1',
    description: 'dominion.games の卓設定を自動的に設定します。',
    author: 'SlashNephy <spica@starry.blue>',
    match: 'https://dominion.games/',
    icon: 'https://www.google.com/s2/favicons?sz=64&domain=dominion.games',
  }),
  buildOptions({
    id: 'ff14angler-bypass-adblock-check',
    name: 'FF14Angler Bypass AdBlock Check',
    version: '0.2.1',
    description: 'FF14Angler の AdBlock チェックを無効にします。',
    author: 'SlashNephy <spica@starry.blue>',
    match: 'https://*.ff14angler.com/*',
    runAt: 'document-body',
    icon: 'https://www.google.com/s2/favicons?sz=64&domain=jp.ff14angler.com',
  }),
  buildOptions({
    id: 'feedly-auto-refresh',
    name: 'Feedly Auto Refresh',
    version: '0.2.1',
    description: 'Feedly で未読記事がないとき、フィードを自動リフレッシュします。',
    author: 'SlashNephy <spica@starry.blue>',
    match: 'https://feedly.com/i/collection/*',
    icon: 'https://www.google.com/s2/favicons?sz=64&domain=feedly.com',
  }),
  buildOptions({
    id: 'amq-preload-video',
    name: 'AMQ Preload Video',
    version: '0.2.0',
    description: 'Just enable media preloading. Speed up buffering.',
    author: 'SlashNephy <spica@starry.blue>',
    match: 'https://animemusicquiz.com/',
    icon: 'https://animemusicquiz.com/favicon-32x32.png',
  }),
  buildOptions({
    id: 'amq-result-exporter',
    name: 'AMQ Result Exporter',
    version: '0.2.0',
    description: 'Export song results to Google Spreadsheet!',
    author: 'SlashNephy <spica@starry.blue>',
    match: 'https://animemusicquiz.com/',
    icon: 'https://animemusicquiz.com/favicon-32x32.png',
    connect: ['script.google.com', 'raw.githubusercontent.com'],
    grant: 'GM_xmlhttpRequest',
  }),
  buildOptions({
    id: 'google-remove-redirection-warning',
    name: 'Google Remove Redirection Warning',
    version: '0.1.0',
    description: 'Remove redirection warning from https://google.com/url',
    author: 'SlashNephy <spica@starry.blue>',
    match: 'https://google.com/url?q=*',
    icon: 'https://www.google.com/s2/favicons?sz=64&domain=google.com',
  }),
  buildOptions({
    id: 'annict-hide-future-programs',
    name: 'Annict Hide Future Programs',
    version: '0.1.0',
    description: 'Annict の「記録するページ」で翌日以降の番組や放送予定が未記入の番組を非表示にします。',
    author: 'SlashNephy <spica@starry.blue>',
    match: 'https://annict.com/*',
    icon: 'https://www.google.com/s2/favicons?sz=64&domain=annict.com',
  }),
  buildOptions({
    id: 'amq-private-session',
    name: 'AMQ Private Session',
    version: '0.2.0',
    description: 'Set invisible status automatically.',
    author: 'SlashNephy <spica@starry.blue>',
    match: 'https://animemusicquiz.com/',
    icon: 'https://animemusicquiz.com/favicon-32x32.png',
  }),
]

export default config
