---
name: 'Check'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'master'

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  lint:
    uses: SlashNephy/.github/.github/workflows/yamllint.yml@master
    permissions:
      contents: 'read'
      pull-requests: 'write'
