name: 'Lint .github/workflows/*.yml'

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'

  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'

  workflow_dispatch:

jobs:
  lint:
    uses: SlashNephy/.github/.github/workflows/actionlint.yml@master
    permissions:
      contents: 'read'
      pull-requests: 'write'
