name: 'Lint Dockerfile'

on:
  push:
    branches:
      - 'master'
    paths:
      - '**/Dockerfile'
      - '**/*.Dockerfile'

  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '**/Dockerfile'
      - '**/*.Dockerfile'

  workflow_dispatch:

jobs:
  lint:
    uses: SlashNephy/.github/.github/workflows/hadolint.yml@master
    permissions:
      contents: 'read'
      pull-requests: 'write'
