name: 'Build eslint-config'

on:
  push:
    paths:
      - 'env/eslint/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: 'env/eslint/yarn.lock'

      - name: Install Dependencies
        working-directory: 'env/eslint'
        run: yarn install

      - name: Build
        run: yarn build
