nodeLinker: node-modules
defaultSemverRangePrefix: ""
enableTelemetry: false
initFields:
  author: "SlashNephy <spica@starry.blue> (https://spica.starry.blue/)"
  license: MIT
progressBarStyle: patrick
