enableGlobalCache: true
compressionLevel: mixed
nodeLinker: node-modules
# MEMO: JetBrains IDE で型定義に飛べなくなる
nmMode: classic
# https://github.com/medusajs/medusa/issues/2181#issuecomment-1284075932
# nmMode: hardlinks-local

defaultSemverRangePrefix: ""

cloneConcurrency: 8
networkConcurrency: 100
workerPoolMode: async

progressBarStyle: patrick

initFields:
  author: "SlashNephy <spica@starry.blue> (https://spica.starry.blue/)"
  license: MIT

npmRegistries:
  "https://registry.yarnpkg.com":
    npmAuthToken: ${NPM_TOKEN:-""}
