nodeLinker: node-modules

# https://github.com/medusajs/medusa/issues/2181#issuecomment-1284075932
nmMode: hardlinks-local
enableGlobalCache: true

defaultSemverRangePrefix: ""
enableTelemetry: false
initFields:
  author: "SlashNephy <spica@starry.blue> (https://spica.starry.blue/)"
  license: MIT
progressBarStyle: patrick

npmRegistries:
  "https://registry.yarnpkg.com":
    npmAuthToken: ${NPM_TOKEN:-""}
