ROOT_DIR="$HOME/.github"

ENV_DIR="$ROOT_DIR/env"
ENV_ARCH_DIR="$ENV_DIR/arch"
ENV_COMMON_DIR="$ENV_DIR/common"
ENV_MACOS_DIR="$ENV_DIR/macos"
ENV_UBUNTU_DIR="$ENV_DIR/ubuntu"
export ENV_ARCH_DIR ENV_COMMON_DIR ENV_MACOS_DIR ENV_UBUNTU_DIR
