name: 'Check env/userstyle'

on:
  push:
    branches:
      - 'master'
    paths:
      - 'env/userstyle/**'
      - '.github/workflows/_check-userstyle.yml'

  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'env/userstyle/**'
      - '.github/workflows/_check-userstyle.yml'

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/yarn-run.yml
    with:
      script: 'workspace @slashnephy/userstyle build'
    permissions:
      contents: 'read'

  lint:
    uses: ./.github/workflows/yarn-lint.yml
    with:
      script: 'workspace @slashnephy/userstyle lint'
      enable-eslint: false
      enable-stylelint: true
    permissions:
      contents: 'read'
      pull-requests: 'write'

  format-and-build-ci:
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/yarn-format.yml
    with:
      script: 'workspace @slashnephy/userstyle ci'
      commit-message: '⚙️ Build (env/userstyle)'
    permissions:
      contents: 'write'
