---
name: 'Check env/stylelint'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'master'
    paths:
      - 'env/stylelint/**'
      - '.github/workflows/_check-stylelint.yml'

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/yarn-run.yml
    with:
      working-directory: 'env/stylelint'
      script: 'build'
    permissions:
      contents: 'read'

  lint:
    uses: ./.github/workflows/yarn-lint.yml
    with:
      working-directory: 'env/stylelint'
    permissions:
      contents: 'read'
      pull-requests: 'write'

  format:
    if: github.event_name == 'push'
    uses: ./.github/workflows/yarn-format.yml
    with:
      working-directory: 'env/stylelint'
      pre-script: 'build'
    permissions:
      contents: 'write'
