name: 'Check scripts'

on:
  push:
    paths:
      - 'scripts/**/*.sh'
      - '.github/workflows/_check-scripts.yml'

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    uses: ./.github/workflows/shellcheck.yml
    permissions:
      contents: 'read'
      pull-requests: 'write'

  test-install-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: bash ~/.github/scripts/install.sh
        env:
          HOME: ..

  test-install-macos:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: bash ~/.github/scripts/install.sh
        env:
          HOME: ..

  test-install-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        shell: powershell
        run: .\scripts\install.ps1
        env:
          USERPROFILE: ..
