name: 'Check env/renovate'

on:
  push:
    branches:
      - 'master'
    paths:
      - 'renovate.json'
      - 'renovate-config.json'
      - 'env/renovate/**'
      - '.github/workflows/_check-renovate.yml'

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/yarn-run.yml
    with:
      working-directory: 'env/renovate'
      script: 'test'

  build:
    uses: ./.github/workflows/yarn-run.yml
    with:
      working-directory: 'env/renovate'
      script: 'build'
    permissions:
      contents: 'read'

  lint:
    uses: ./.github/workflows/yarn-lint.yml
    with:
      working-directory: 'env/renovate'
    permissions:
      contents: 'read'
      pull-requests: 'write'

  format:
    if: github.event_name == 'push'
    uses: ./.github/workflows/yarn-format.yml
    with:
      working-directory: 'env/renovate'
    permissions:
      contents: 'write'
