name: 'Check env/renovate'

on:
  push:
    branches:
      - 'master'
    paths:
      - 'renovate.json'
      - 'renovate-config.json'
      - 'env/renovate/**'
      - '.github/workflows/_check-renovate.yml'

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/run-yarn.yml
    with:
      working-directory: 'env/renovate'
      script: 'test'

  lint:
    uses: ./.github/workflows/run-yarn.yml
    with:
      working-directory: 'env/renovate'
      script: 'lint'

  format:
    if: github.event_name == 'push'
    uses: ./.github/workflows/format-node.yml
    with:
      working-directory: 'env/renovate'
