name: 'Check .github/workflows'

on:
  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/actionlint.yml
    permissions:
      contents: 'read'
      pull-requests: 'write'
