name: 'Check .github/workflows'

on:
  push:
    paths:
      - '.github/workflows/*.yml'

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/actionlint.yml
    permissions:
      contents: 'read'
      pull-requests: 'write'
