name: 'Check env/typescript'

on:
  push:
    branches:
      - 'master'
    paths:
      - 'env/typescript/**'
      - '.github/workflows/_check-typescript.yml'

  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'env/typescript/**'
      - '.github/workflows/_check-typescript.yml'

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/yarn-run.yml
    with:
      script: 'workspace @slashnephy/typescript-extension build'
    permissions:
      contents: 'read'

  lint:
    uses: ./.github/workflows/yarn-lint.yml
    with:
      script: 'workspace @slashnephy/typescript-extension lint'
    permissions:
      contents: 'read'
      pull-requests: 'write'

  format:
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/yarn-format.yml
    with:
      script: 'workspace @slashnephy/typescript-extension format'
    permissions:
      contents: 'write'

  publish:
    if: github.event_name == 'push'
    needs:
      - build
      - lint
    uses: ./.github/workflows/yarn-publish.yml
    with:
      script: 'workspace @slashnephy/typescript-extension publish'
    permissions:
      contents: 'write'
    secrets:
      NODE_AUTH_TOKEN: '${{ secrets.NPM_ACCESS_TOKEN }}'
