---
name: 'Check .github/workflows'

# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - '.github/workflows/*.yml'

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  actionlint:
    uses: ./.github/workflows/actionlint.yml
    permissions:
      contents: 'read'
      pull-requests: 'write'

  yamllint:
    uses: ./.github/workflows/yamllint.yml
    permissions:
      contents: 'read'
      pull-requests: 'write'
