name: 'Check env/eslint'

on:
  push:
    paths:
      - 'env/eslint/**'
      - '.github/workflows/_check-eslint.yml'

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/run-yarn.yml
    with:
      working-directory: 'env/eslint'
      script: 'build'

  lint:
    uses: ./.github/workflows/run-yarn.yml
    with:
      working-directory: 'env/eslint'
      script: 'lint'

  format:
    if: github.event_name == 'push'
    uses: ./.github/workflows/format-node.yml
    with:
      working-directory: 'env/eslint'
