name: 'Check env/discord'

on:
  push:
    branches:
      - 'master'
    paths:
      - 'env/discord/**'
      - '!env/discord/plugins/**'
      - '!env/discord/themes/**'
      - '.github/workflows/_check-discord.yml'

  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'env/discord/**'
      - '!env/discord/plugins/**'
      - '!env/discord/themes/**'
      - '.github/workflows/_check-discord.yml'

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/yarn-run.yml
    with:
      working-directory: 'env/discord'
      script: 'build'
    permissions:
      contents: 'read'

  lint:
    uses: ./.github/workflows/yarn-lint.yml
    with:
      script: 'workspace @slashnephy/discord lint'
    permissions:
      contents: 'read'
      pull-requests: 'write'

  format:
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/yarn-format.yml
    with:
      script: 'workspace @slashnephy/discord format'
    permissions:
      contents: 'write'

  bundle:
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/yarn-format.yml
    with:
      script: 'workspace @slashnephy/discord bundle'
      commit-message: '⚙️ Build (env/discord)'
    permissions:
      contents: 'write'
