name: 'Check env/renovate'

on:
  push:
    branches:
      - 'master'
    paths:
      - 'renovate.json'
      - 'renovate-config.json'
      - 'env/renovate/**'
      - '.github/workflows/_check-renovate.yml'

  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'renovate.json'
      - 'renovate-config.json'
      - 'env/renovate/**'
      - '.github/workflows/_check-renovate.yml'

  workflow_dispatch:

  #  schedule:
  #    - cron: '0 0 * * *'

jobs:
  test:
    if: github.event_name != 'schedule'
    uses: ./.github/workflows/yarn-run.yml
    with:
      working-directory: 'env/renovate'
      script: 'test'

  build:
    if: github.event_name != 'schedule'
    uses: ./.github/workflows/yarn-run.yml
    with:
      script: 'workspace @slashnephy/renovate-config build'
    permissions:
      contents: 'read'

  lint:
    if: github.event_name != 'schedule'
    uses: ./.github/workflows/yarn-lint.yml
    with:
      script: 'workspace @slashnephy/renovate-config lint'
    permissions:
      contents: 'read'
      pull-requests: 'write'

  format:
    if: github.event_name != 'pull_request' && github.event_name != 'schedule'
    uses: ./.github/workflows/yarn-format.yml
    with:
      script: 'workspace @slashnephy/renovate-config format'
    permissions:
      contents: 'write'

  #  update:
  #    if: github.event_name != 'pull_request'
  #    uses: ./.github/workflows/yarn-run.yml
  #    with:
  #      working-directory: 'env/renovate'
  #      script: 'start'
  #      env: GITHUB_TOKEN=${{ secrets.GH_PAT }}
  #    permissions:
  #      contents: 'read'
