name: 'Check env/discord'

on:
  push:
    branches:
      - 'master'
    paths:
      - 'env/discord/**'
      - '.github/workflows/_check-discord.yml'
    paths-ignore:
      - 'env/discord/plugins/**'
      - 'env/discord/themes/**'

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/yarn-run.yml
    with:
      working-directory: 'env/discord'
      script: 'build'
    permissions:
      contents: 'read'

  lint:
    uses: ./.github/workflows/yarn-lint.yml
    with:
      working-directory: 'env/discord'
    permissions:
      contents: 'read'
      pull-requests: 'write'

  format:
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/yarn-format.yml
    with:
      working-directory: 'env/discord'
    permissions:
      contents: 'write'

  bundle:
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/yarn-format.yml
    with:
      working-directory: 'env/discord'
      script: 'bundle'
      commit-message: '⚙️ Build (env/discord)'
    permissions:
      contents: 'write'
