name: 'Check env/eslint'

on:
  push:
    paths:
      - 'env/eslint/**'

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  build:
    if: github.event == 'pull_request' || github.event == 'workflow_dispatch'
    uses: ./.github/workflows/run-yarn.yml
    with:
      working-directory: 'env/eslint'
      script: 'build'

  lint:
    if: github.event == 'pull_request' || github.event == 'workflow_dispatch'
    uses: ./.github/workflows/run-yarn.yml
    with:
      working-directory: 'env/eslint'
      script: 'lint'

  format:
    if: github.event == 'push'
    uses: ./.github/workflows/format-node.yml
    with:
      working-directory: 'env/eslint'
