name: 'Check env/eslint'

on:
  push:
    branches:
      - 'master'
    paths:
      - 'env/eslint/**'
      - '.github/workflows/_check-eslint.yml'

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/lint-node.yml
    with:
      working-directory: 'env/eslint'
      pre-script: 'build'

  format:
    if: github.event_name == 'push'
    uses: ./.github/workflows/format-node.yml
    with:
      working-directory: 'env/eslint'
      pre-script: 'build'
