name: 'Check env/renovate'

on:
  push:
    paths:
      - 'renovate.json'
      - 'renovate-config.json'
      - 'env/renovate/**'

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  build:
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/run-yarn.yml
    with:
      working-directory: 'env/renovate'
      script: 'build'

  lint:
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/run-yarn.yml
    with:
      working-directory: 'env/renovate'
      script: 'lint'

  format:
    if: github.event_name == 'push'
    uses: ./.github/workflows/format-node.yml
    with:
      working-directory: 'env/renovate'
