name: 'Build yarn project'

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: .

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: '${{ inputs.working-directory }}/yarn.lock'

      - name: Install Dependencies
        working-directory: ${{ inputs.working-directory }}
        run: yarn install

      - name: Build
        run: yarn build
