name: Test

on:
  push:
  workflow_dispatch:

env:
  SKIP_PROMPT: 1

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: bash ~/.github/scripts/install.sh
        env:
          HOME: .

  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: bash ~/.github/scripts/install.sh
        env:
          HOME: .

  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        shell: powershell
        run: .\scripts\install-windows.ps1
