name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: bash ~/.github/scripts/install.sh
        env:
          HOME: ..

  test-macos:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: bash ~/.github/scripts/install.sh
        env:
          HOME: ..

  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        shell: powershell
        run: .\scripts\install.ps1
        env:
          USERPROFILE: ..
