name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install zsh
        run: sudo apt update && sudo apt install -y zsh
      - name: Test
        run: zsh ./env/install.zsh

  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: zsh ./env/install.zsh

  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        shell: powershell
        run: .\env\install-windows.ps1
